python request_source.py haul $BUCKET_NAME haul 1982
python request_source.py haul $BUCKET_NAME haul 1983
python request_source.py haul $BUCKET_NAME haul 1984
python request_source.py haul $BUCKET_NAME haul 1985
python request_source.py haul $BUCKET_NAME haul 1986
python request_source.py haul $BUCKET_NAME haul 1987
python request_source.py haul $BUCKET_NAME haul 1988
python request_source.py haul $BUCKET_NAME haul 1989
python request_source.py haul $BUCKET_NAME haul 1990
python request_source.py haul $BUCKET_NAME haul 1991
python request_source.py haul $BUCKET_NAME haul 1992
python request_source.py haul $BUCKET_NAME haul 1993
python request_source.py haul $BUCKET_NAME haul 1994
python request_source.py haul $BUCKET_NAME haul 1995
python request_source.py haul $BUCKET_NAME haul 1996
python request_source.py haul $BUCKET_NAME haul 1997
python request_source.py haul $BUCKET_NAME haul 1998
python request_source.py haul $BUCKET_NAME haul 1999
python request_source.py haul $BUCKET_NAME haul 2000
python request_source.py haul $BUCKET_NAME haul 2001
python request_source.py haul $BUCKET_NAME haul 2002
python request_source.py haul $BUCKET_NAME haul 2003
python request_source.py haul $BUCKET_NAME haul 2004
python request_source.py haul $BUCKET_NAME haul 2005
python request_source.py haul $BUCKET_NAME haul 2006
python request_source.py haul $BUCKET_NAME haul 2007
python request_source.py haul $BUCKET_NAME haul 2008
python request_source.py haul $BUCKET_NAME haul 2009
python request_source.py haul $BUCKET_NAME haul 2010
python request_source.py haul $BUCKET_NAME haul 2011
python request_source.py haul $BUCKET_NAME haul 2012
python request_source.py haul $BUCKET_NAME haul 2013
python request_source.py haul $BUCKET_NAME haul 2014
python request_source.py haul $BUCKET_NAME haul 2015
python request_source.py haul $BUCKET_NAME haul 2016
python request_source.py haul $BUCKET_NAME haul 2017
python request_source.py haul $BUCKET_NAME haul 2018
python request_source.py haul $BUCKET_NAME haul 2019
python request_source.py haul $BUCKET_NAME haul 2020
python request_source.py haul $BUCKET_NAME haul 2021
python request_source.py haul $BUCKET_NAME haul 2022
python request_source.py haul $BUCKET_NAME haul 2023
python request_source.py haul $BUCKET_NAME haul 2024
python request_source.py catch $BUCKET_NAME catch
